# Generated by Django 2.2.7 on 2019-11-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20191106_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='city_n',
        ),
    ]
