# Generated by Django 2.2.7 on 2019-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20191106_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.DeleteModel(
            name='city_n',
        ),
    ]
